sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with docker file"
  - docker build -t swa05142/docker-vue-app -f Dockerfile.dev .

script:
  - docker build -t swa05142/docker-vue-app ./frontend
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin
  - docker push swa05142/docker-vue-app

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "Nabi"
  env: "Nabi-env-1"
  bucket_name: "elasticbeanstalk-ap-northeast-1-710107323718"
  bucket_path: "Nabi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  skip_cleanup: true
