version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    stdin_open: true